### ISSUE TITLE
did not parse as a facility

### ISSUE THREAD

**Issue by ambroseyo** [Phillipmartin/gopassivedns#23]
Hi, I just did a fresh install on Ubuntu 16.04.1 LTS on i686 architecture and am getting an error when running. I have 2 monitor/SPAN interfaces, enp5s0f1 and enp9s2. Both interfaces show the same error when running gopassivedns with only the -dev option specifid: FATA[0000] string '' did not parse as a facility

Sometimes it decodes 1 query, but usually it just fails with the error as seen below.

root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp5s0f1
FATA[0000] string '' did not parse as a facility
root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp5s0f1
FATA[0000] string '' did not parse as a facility
root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp5s0f1
FATA[0000] string '' did not parse as a facility
root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp5s0f1
{"query_id":41507,"response_code":0,"question":"<DOMAIN_REMOVED>","question_type":"A","answer":"<IP_REMOVED>","answer_type":"A","ttl":195,"server":"<IP_REMOVED>","client":"<IP_REMOVED>","timestamp":"2016-12-01T22:43:23Z"}
FATA[0000] string '' did not parse as a facility

root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp9s2
FATA[0000] string '' did not parse as a facility
root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp9s2
{"query_id":53889,"response_code":0,"question":"<DOMAIN_REMOVED>","question_type":"A","answer":"<IP_REMOVED>","answer_type":"A","ttl":24,"server":"<IP_REMOVED>","client":"<IP_REMOVED>","timestamp":"2016-12-01T22:49:35Z"}
FATA[0000] string '' did not parse as a facility
root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp9s2
FATA[0000] string '' did not parse as a facility
root@ns-mon-1:~/gopassivedns# ./gopassivedns -dev enp9s2
FATA[0000] string '' did not parse as a facility

root@ns-mon-1:~# uname -a
Linux ns-mon-1 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:17 UTC 2016 i686 i686 i686 GNU/Linux

root@ns-mon-1:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

Please let me know if there is any other info required to help understand why it's not working as expected.

Thanks

**Comment by wetnun** [comment]
I ran into this as well.  One of the syslog options defaults and the other doesn't.  so the test to see if you want to use syslog if flawed.  If you pass in an empty string for both syslog options the issue goes away.  Getting this fixed would be nice.

**Comment by Phillipmartin** [comment]
yup, logic bug.  Give the code on https://github.com/Phillipmartin/gopassivedns/tree/bugfix/parse_as_feature a try and see if that solves it for you.

**Comment by wetnun** [comment]
Looks good to me.
