### ISSUE TITLE
FR: Support arbitrary syslog facilities

### ISSUE THREAD

**Issue by jaredledvina** [Phillipmartin/gopassivedns#24]
Due to the log volume from gopassivedns, we'd like to configure it to log to a specific syslog facility to further separate it out from the rest of the system logs. However it seems that, https://github.com/Phillipmartin/gopassivedns/blob/aa047e156339bc54f46cf6ccc7fa99f24d94c9d2/log.go#L244-L283 restricts the providers.

**Comment by Phillipmartin** [comment]
I'm not sure what you're looking for here.  Syslog facilities are defined in https://tools.ietf.org/html/rfc3164, as far as I know you can't add arbitrary new ones.  Mostly people handle this by using one of the local* facilities.  Could you tell me a little more about what you would like this to look like?

**Comment by jaredledvina** [comment]
Ah whoops, I meant to superceed this with https://github.com/Phillipmartin/gopassivedns/issues/25 but apparently missed actually doing that. Sorry!
