### ISSUE TITLE
FR: Configurable syslog tag

### ISSUE THREAD

**Issue by jaredledvina** [Phillipmartin/gopassivedns#25]
I'd like to be able to configure the tag that gopassivedns passes to syslog. It appears it's currently hardcoded to `/usr/sbin/gopassivedns[12406]:`. Ideally, I'd be able to simply have them set as `gopassivedns`.

**Comment by Phillipmartin** [comment]
easy enough, I just need to add a config option and put it as the second option on https://github.com/Phillipmartin/gopassivedns/blob/master/log.go#L230.  I'll get to that as soon as I have free time (alternatively, PRs accepted)

**Comment by Phillipmartin** [comment]
https://github.com/Phillipmartin/gopassivedns/pull/28 should add this support.  please test and let me know how it works for you.
