### ISSUE TITLE
gopassivedns -dev eth0 not receiving anything

### ISSUE THREAD

**Issue by heipei** [Phillipmartin/gopassivedns#34]
Hello,

just tried using gopassivedns on a Ubuntu 16.04 box. Reading from PCAP works fine, but when I start it on eth0, nothing happens, no output, no errors. gopassivedns version is e879ce4.

`./gopassivedns -dev eth0 -debug
DEBU[0000] STDOUT logging enabled`

Also the interface does not switch into promiscuous mode.

Let me know what I should do to debug this. FWIW, the interface has a second IPv4 address via `ip addr` I can provide an strace to you privately.

**Comment by Phillipmartin** [comment]
let's get some basic questions out of the way up front:

Is there DNS traffic to observe on the interface in question?  
Have you tried generating lookups on the system to see if they show up in the log?
Are you running as root or via sudo (for the promiscuous flag)?

**Comment by heipei** [comment]
Damn it, I thought I amended this issue. I figured it out five minutes later, for some reason I used the binary shipped with the release rather than building it myself. After building it it works flawlessly now, thanks!
